### ISSUE TITLE
Child processes are never waited for and become zombies

### ISSUE THREAD

**Issue by jkjuopperi** [kemayo/irssi-pushover#1]
Seems that the forked child processes are left as zombies in the process list. They need to be wait():ed for or completely detached from the main process (setsid()?)

 8881 29843  8881  8655 pts/1091  8881 Z+    4479   0:00 [irssi] <defunct>
 8881 30129  8881  8655 pts/1091  8881 Z+    4479   0:00 [irssi] <defunct>
 8881 30319  8881  8655 pts/1091  8881 Z+    4479   0:00 [irssi] <defunct>
 8881 30888  8881  8655 pts/1091  8881 Z+    4479   0:00 [irssi] <defunct>
 8881 30935  8881  8655 pts/1091  8881 Z+    4479   0:00 [irssi] <defunct>
 8881 31709  8881  8655 pts/1091  8881 Z+    4479   0:00 [irssi] <defunct>

**Comment by kemayo** [comment]
Tiny delay in responding, but I fixed this with 4adb54c.
